<?php
    echo '<section>';
        echo '<h2>Contact Us</h2>';
        echo '<a href="mailto:jkltech@gmail.com"><i class="fa fa-envelope"></i>Email</a>';
        echo '<a><i class="fa fa-phone"></i>Phone</a>';
        echo '<a target="_blank" href="https://maps.app.goo.gl/iwJz7yzzg6kSjBNb6"><i class="fa fa-home"></i>Location</a>';
    echo '</section>';
    echo '<section>';
        echo '<img src="images/logo-dark.png" alt="JKL Tech Company Logo">'; 
    echo '</section>';
    echo '<section>';
        echo '<h2>Quick Links</h2>';
        echo '<a href="index.php">Home</a>';
        echo '<a href="about.php">About</a>';
        echo '<a href="jobs.php">Jobs</a>';
        echo '<a href="apply.php">Apply</a>';
        echo '<a href="enhancements.php">Enhancements</a>';
	echo '<a href="login.php">Login</a>';
    echo '</section>';
?>